
CREATE TABLE "SERVER_CENTRAL"."ADMINISTRADOR" 
   (	"PER_CEDULA" NUMBER(*,0) NOT NULL ENABLE, 
	"HOS_NOMBRE" CHAR(50), 
	"ADM_USUARIO" CHAR(25) NOT NULL ENABLE, 
	"ADM_CONTRASENA" CHAR(10) NOT NULL ENABLE, 
	"ADM_CARGO" CHAR(15) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ADMINISTRADOR" PRIMARY KEY ("PER_CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS" ;

ALTER TABLE "SERVER_CENTRAL"."ADMINISTRADOR" ADD CONSTRAINT "FK_ADMINIST_ES2_PERSONA" FOREIGN KEY ("PER_CEDULA")
	  REFERENCES "SERVER_CENTRAL"."PERSONA" ("PER_CEDULA") ENABLE;
  ALTER TABLE "SERVER_CENTRAL"."ADMINISTRADOR" ADD CONSTRAINT "FK_ADMINIST_TRABAJA_HOPITAL" FOREIGN KEY ("HOS_NOMBRE")
	  REFERENCES "SERVER_CENTRAL"."HOSPITAL" ("HOS_NOMBRE") ENABLE;

CREATE UNIQUE INDEX "SERVER_CENTRAL"."PK_ADMINISTRADOR" ON "SERVER_CENTRAL"."ADMINISTRADOR" ("PER_CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS" ;
  CREATE INDEX "SERVER_CENTRAL"."TRABAJA_FK" ON "SERVER_CENTRAL"."ADMINISTRADOR" ("HOS_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS" ;

CREATE TABLE "SERVER_CENTRAL"."CAMA" 
   (	"ID_CAMA" CHAR(100) NOT NULL ENABLE, 
	"ESPE_NOMBRE" CHAR(50), 
	"CAM_ESTADO" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CAMA" PRIMARY KEY ("ID_CAMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SERVER_CENTRAL_TS" ;

ALTER TABLE "SERVER_CENTRAL"."CAMA" ADD CONSTRAINT "FK_CAMA_TIENE_ESPECIAL" FOREIGN KEY ("ESPE_NOMBRE")
	  REFERENCES "SERVER_CENTRAL"."ESPECIALIDAD" ("ESPE_NOMBRE") ENABLE;

CREATE UNIQUE INDEX "SERVER_CENTRAL"."PK_CAMA" ON "SERVER_CENTRAL"."CAMA" ("ID_CAMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS" ;
  CREATE INDEX "SERVER_CENTRAL"."TIENE_FK" ON "SERVER_CENTRAL"."CAMA" ("ESPE_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS" ;

CREATE TABLE "SERVER_CENTRAL"."DERIVAN" 
   (	"DEV_FECHA_ENTRADA" DATE, 
	"DEV_FECHA_SALIDA" DATE, 
	"DEV_ESTADO" CLOB, 
	"ID_CAMA" CHAR(100) NOT NULL ENABLE, 
	"PER_CEDULA" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_DERIVAN" PRIMARY KEY ("ID_CAMA", "PER_CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SERVER_CENTRAL_TS" 
 LOB ("DEV_ESTADO") STORE AS SECUREFILE (
  TABLESPACE "SERVER_CENTRAL_TS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

ALTER TABLE "SERVER_CENTRAL"."DERIVAN" ADD CONSTRAINT "FK_DERIVAN_DERIVAN_CAMA" FOREIGN KEY ("ID_CAMA")
	  REFERENCES "SERVER_CENTRAL"."CAMA" ("ID_CAMA") ENABLE;
  ALTER TABLE "SERVER_CENTRAL"."DERIVAN" ADD CONSTRAINT "FK_DERIVAN_DERIVAN2_PACIENTE" FOREIGN KEY ("PER_CEDULA")
	  REFERENCES "SERVER_CENTRAL"."PACIENTE" ("PER_CEDULA") ENABLE;

CREATE UNIQUE INDEX "SERVER_CENTRAL"."PK_DERIVAN" ON "SERVER_CENTRAL"."DERIVAN" ("ID_CAMA", "PER_CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS" ;
  CREATE UNIQUE INDEX "SERVER_CENTRAL"."SYS_IL0000080175C00003$$" ON "SERVER_CENTRAL"."DERIVAN" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "SERVER_CENTRAL"."DERIVAN2_FK" ON "SERVER_CENTRAL"."DERIVAN" ("PER_CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS" ;
  CREATE INDEX "SERVER_CENTRAL"."DERIVAN_FK" ON "SERVER_CENTRAL"."DERIVAN" ("ID_CAMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS" ;

COMMENT ON COLUMN SERVER_CENTRAL.DERIVAN.ID_CAMA IS 'Es un identificar unico asignado a cada cama.';

CREATE TABLE "SERVER_CENTRAL"."ESPECIALIDAD" 
   (	"ESPE_NOMBRE" CHAR(50) NOT NULL ENABLE, 
	"ESPE_DESCRIPCION" CHAR(50) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ESPECIALIDAD" PRIMARY KEY ("ESPE_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SERVER_CENTRAL_TS" ;

CREATE UNIQUE INDEX "SERVER_CENTRAL"."PK_ESPECIALIDAD" ON "SERVER_CENTRAL"."ESPECIALIDAD" ("ESPE_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS" ;

COMMENT ON TABLE SERVER_CENTRAL.ESPECIALIDAD IS 'Indica el tipo de atención médica que se proporciona en una cama específica. ';
COMMENT ON COLUMN SERVER_CENTRAL.ESPECIALIDAD.ESPE_NOMBRE IS 'Es el nombre de la especialización. Describe el área específica de la medicina o el campo de especialización al que se refiere esta entidad.';
COMMENT ON COLUMN SERVER_CENTRAL.ESPECIALIDAD.ESPE_DESCRIPCION IS 'Proporciona una descripción adicional de la especialización. ';

CREATE TABLE "SERVER_CENTRAL"."HOSPITAL" 
   (	"ID_ZONA" CHAR(20) NOT NULL ENABLE, 
	"HOS_NOMBRE" CHAR(50) NOT NULL ENABLE, 
	"HOS_TELEFONO" NUMBER(*,0) NOT NULL ENABLE, 
	"HOS_CORREO" CHAR(50), 
	"HOS_SITIO_WEB" CHAR(50), 
	 CONSTRAINT "PK_HOPITAL" PRIMARY KEY ("HOS_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS" ;

ALTER TABLE "SERVER_CENTRAL"."HOSPITAL" ADD CONSTRAINT "FK_HOPITAL_SITUA2_ZONA" FOREIGN KEY ("ID_ZONA")
	  REFERENCES "SERVER_CENTRAL"."ZONA" ("ID_ZONA") ENABLE;

CREATE UNIQUE INDEX "SERVER_CENTRAL"."PK_HOPITAL" ON "SERVER_CENTRAL"."HOSPITAL" ("HOS_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS" ;
  CREATE INDEX "SERVER_CENTRAL"."SITUA2_FK" ON "SERVER_CENTRAL"."HOSPITAL" ("ID_ZONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS" ;

COMMENT ON TABLE SERVER_CENTRAL.HOSPITAL IS 'Representa la institución médica en sí misma. ';
COMMENT ON COLUMN SERVER_CENTRAL.HOSPITAL.ID_ZONA IS 'Este es un identificador único asignado a cada zona en la base de datos del sistema';
COMMENT ON COLUMN SERVER_CENTRAL.HOSPITAL.HOS_NOMBRE IS 'Es el nombre del hospital. Sirve para identificar el hospital de manera legible y fácilmente reconocible.';
COMMENT ON COLUMN SERVER_CENTRAL.HOSPITAL.HOS_TELEFONO IS 'Es el número de teléfono del hospital. Se utiliza como medio de contacto para comunicarse con el hospital.';
COMMENT ON COLUMN SERVER_CENTRAL.HOSPITAL.HOS_CORREO IS 'Es la dirección de correo electrónico asociada al hospital. Se utiliza para la comunicación electrónica con el hospital y puede ser una forma importante de contacto.';
COMMENT ON COLUMN SERVER_CENTRAL.HOSPITAL.HOS_SITIO_WEB IS 'Es la dirección URL del sitio web del hospital. Proporciona información adicional sobre el hospital.';

CREATE TABLE "SERVER_CENTRAL"."HOSPITALTIENEESPECIALIDAD" 
   (	"ESPE_NOMBRE" CHAR(50) NOT NULL ENABLE, 
	"HOS_NOMBRE" CHAR(50) NOT NULL ENABLE, 
	 CONSTRAINT "PK_HOSPITALTIENEESPECIALIDAD" PRIMARY KEY ("ESPE_NOMBRE", "HOS_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SERVER_CENTRAL_TS" ;

ALTER TABLE "SERVER_CENTRAL"."HOSPITALTIENEESPECIALIDAD" ADD CONSTRAINT "FK_HOSPITAL_HOSPITALT_ESPECIAL" FOREIGN KEY ("ESPE_NOMBRE")
	  REFERENCES "SERVER_CENTRAL"."ESPECIALIDAD" ("ESPE_NOMBRE") ENABLE;
  ALTER TABLE "SERVER_CENTRAL"."HOSPITALTIENEESPECIALIDAD" ADD CONSTRAINT "FK_HOSPITAL_TIENE2_HOPITAL" FOREIGN KEY ("HOS_NOMBRE")
	  REFERENCES "SERVER_CENTRAL"."HOSPITAL" ("HOS_NOMBRE") ENABLE;

CREATE UNIQUE INDEX "SERVER_CENTRAL"."PK_HOSPITALTIENEESPECIALIDAD" ON "SERVER_CENTRAL"."HOSPITALTIENEESPECIALIDAD" ("ESPE_NOMBRE", "HOS_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS" ;
  CREATE INDEX "SERVER_CENTRAL"."TIENE2_FK" ON "SERVER_CENTRAL"."HOSPITALTIENEESPECIALIDAD" ("HOS_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS" ;
  CREATE INDEX "SERVER_CENTRAL"."HOSPITALTIENEESPECIALIDAD2_FK" ON "SERVER_CENTRAL"."HOSPITALTIENEESPECIALIDAD" ("ESPE_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS" ;

COMMENT ON COLUMN SERVER_CENTRAL.HOSPITALTIENEESPECIALIDAD.ESPE_NOMBRE IS 'Es el nombre de la especialización. Describe el área específica de la medicina o el campo de especialización al que se refiere esta entidad.';
COMMENT ON COLUMN SERVER_CENTRAL.HOSPITALTIENEESPECIALIDAD.HOS_NOMBRE IS 'Es el nombre del hospital. Sirve para identificar el hospital de manera legible y fácilmente reconocible.';

CREATE TABLE "SERVER_CENTRAL"."PACIENTE" 
   (	"PER_CEDULA" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_ZONA" CHAR(20), 
	"PAC_HISTORIAL" CLOB NOT NULL ENABLE, 
	 CONSTRAINT "PK_PACIENTE" PRIMARY KEY ("PER_CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SERVER_CENTRAL_TS" 
 LOB ("PAC_HISTORIAL") STORE AS SECUREFILE (
  TABLESPACE "SERVER_CENTRAL_TS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

ALTER TABLE "SERVER_CENTRAL"."PACIENTE" ADD CONSTRAINT "FK_PACIENTE_ES_PERSONA" FOREIGN KEY ("PER_CEDULA")
	  REFERENCES "SERVER_CENTRAL"."PERSONA" ("PER_CEDULA") ENABLE;
  ALTER TABLE "SERVER_CENTRAL"."PACIENTE" ADD CONSTRAINT "FK_PACIENTE_PROVIENE_ZONA" FOREIGN KEY ("ID_ZONA")
	  REFERENCES "SERVER_CENTRAL"."ZONA" ("ID_ZONA") ENABLE;

CREATE UNIQUE INDEX "SERVER_CENTRAL"."PK_PACIENTE" ON "SERVER_CENTRAL"."PACIENTE" ("PER_CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS" ;
  CREATE UNIQUE INDEX "SERVER_CENTRAL"."SYS_IL0000080190C00003$$" ON "SERVER_CENTRAL"."PACIENTE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "SERVER_CENTRAL"."PROVIENE_FK" ON "SERVER_CENTRAL"."PACIENTE" ("ID_ZONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SERVER_CENTRAL_TS" ;

COMMENT ON TABLE SERVER_CENTRAL.PACIENTE IS 'Son loos individuos que requieren atención médica en el hospital.';
COMMENT ON COLUMN SERVER_CENTRAL.PACIENTE.PER_CEDULA IS 'Es un identificador único asignado a cada persona. Se utiliza para identificar de manera única a un individuo en el sistema.';
COMMENT ON COLUMN SERVER_CENTRAL.PACIENTE.ID_ZONA IS 'Este es un identificador único asignado a cada zona en la base de datos del sistema';

CREATE TABLE "SERVER_CENTRAL"."PERSONA" 
   (	"PER_CEDULA" NUMBER(10,0) NOT NULL ENABLE, 
	"PER_NOMBRES" CHAR(50) NOT NULL ENABLE, 
	"PER_APELLIDOS" CHAR(50) NOT NULL ENABLE, 
	"PER_TELEFONO" NUMBER(10,0), 
	"PER_CORREO" CHAR(25), 
	"PER_GENERO" CHAR(9) NOT NULL ENABLE, 
	 CONSTRAINT "CKC_PER_GENERO_PERSONA" CHECK (PER_GENERO in ('Masculino','Femenino')) ENABLE, 
	 CONSTRAINT "PK_PERSONA" PRIMARY KEY ("PER_CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS" ;



CREATE TABLE "SERVER_CENTRAL"."ZONA" 
   (	"ID_ZONA" CHAR(20) NOT NULL ENABLE, 
	"ZONA_CALLE_PRINCIPAL" CHAR(50) NOT NULL ENABLE, 
	"ZONA_CALLER_SECUNDARIA" CHAR(50), 
	"ZONA_REFERENCIA" CHAR(50) NOT NULL ENABLE, 
	"ZONA_PARROQUIA" CHAR(50) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ZONA" PRIMARY KEY ("ID_ZONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS" ;

CREATE UNIQUE INDEX "SERVER_CENTRAL"."PK_ZONA" ON "SERVER_CENTRAL"."ZONA" ("ID_ZONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SERVER_CENTRAL_TS" ;

